import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "../components/navbar";
import Card from "../components/card";
import { FunctionComponent } from "react";

const Home: FunctionComponent<NextPage> = () => {
  return (
    <>
      <Head>
        <title>ARC Blog | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-blue-light min-h-screen h-full">
        <header className="bg-dark w-full py-8 px-24">
          <Navbar />
        </header>

        <main className="bg-transparent w-full container mx-auto py-12">
          <div className="flex flex-col">
            <div className="text-left mb-6">
              <p className="font-inter text-dark text-4xl font-bold">
                Lastest Article
              </p>
            </div>
            <div className="grid grid-flow-row grid-cols-3 gap-24">
              <Card
                author="Raihan Adam"
                category="Programming"
                excerpt="Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Eveniet, similique"
                title="Lorem, ipsum."
                slugAuthor="raihan-adam"
                slugCategory="programming"
                slugTitle="lorem-ipsum"
              />
              <div className="rounded-xl bg-transparent border-dark border-opacity-60 border-2 p-6">
                <div className="flex flex-col">
                  <div className="flex flex-row justify-between items-center">
                    <h1 className="text-dark font-inter text-3xl font-semibold">
                      Lorem, ipsum.
                    </h1>
                    <p className="text-dark font-inter font-medium">
                      by <a href="/">Raihan Adam</a>
                    </p>
                  </div>
                  <p className="text-dark font-inter mt-4 mb-1">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Eveniet, similique...
                  </p>
                  <a
                    href="#"
                    className="underline hover:no-underline text-dark font-inter"
                  >
                    Read More...
                  </a>
                  <p className="text-dark font-inter text-lg font-medium mt-4">
                    Category: <a href="/">Programming</a>
                  </p>
                </div>
              </div>
              <div className="rounded-xl bg-transparent border-dark border-opacity-60 border-2 p-6">
                <div className="flex flex-col">
                  <h1 className="text-dark font-inter text-3xl font-semibold">
                    Lorem, ipsum.
                  </h1>
                  <p className="text-dark font-inter mt-4 mb-1">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Eveniet, similique...
                  </p>
                  <a
                    href="#"
                    className="underline hover:no-underline text-dark font-inter"
                  >
                    Read More...
                  </a>
                  <p className="text-dark font-inter text-lg font-medium mt-4">
                    Category: <a href="/">Programming</a>
                  </p>
                </div>
              </div>
              <div className="rounded-xl bg-transparent border-dark border-opacity-60 border-2 p-6">
                <div className="flex flex-col">
                  <h1 className="text-dark font-inter text-3xl font-semibold">
                    Lorem, ipsum.
                  </h1>
                  <p className="text-dark font-inter mt-4 mb-1">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Eveniet, similique...
                  </p>
                  <a
                    href="#"
                    className="underline hover:no-underline text-dark font-inter"
                  >
                    Read More...
                  </a>
                  <p className="text-dark font-inter text-lg font-medium mt-4">
                    Category: <a href="/">Programming</a>
                  </p>
                </div>
              </div>
              <div className="rounded-xl bg-transparent border-dark border-opacity-60 border-2 p-6">
                <div className="flex flex-col">
                  <h1 className="text-dark font-inter text-3xl font-semibold">
                    Lorem, ipsum.
                  </h1>
                  <p className="text-dark font-inter mt-4 mb-1">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Eveniet, similique...
                  </p>
                  <a
                    href="#"
                    className="underline hover:no-underline text-dark font-inter"
                  >
                    Read More...
                  </a>
                  <p className="text-dark font-inter text-lg font-medium mt-4">
                    Category: <a href="/">Programming</a>
                  </p>
                </div>
              </div>
              <div className="rounded-xl bg-transparent border-dark border-opacity-60 border-2 p-6">
                <div className="flex flex-col">
                  <h1 className="text-dark font-inter text-3xl font-semibold">
                    Lorem, ipsum.
                  </h1>
                  <p className="text-dark font-inter mt-4 mb-1">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Eveniet, similique...
                  </p>
                  <a
                    href="#"
                    className="underline hover:no-underline text-dark font-inter"
                  >
                    Read More...
                  </a>
                  <p className="text-dark font-inter text-lg font-medium mt-4">
                    Category: <a href="/">Programming</a>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </main>
      </div>
    </>
  );
};

export default Home;
